In [87]:
#KABUNGA AKRAM JOSHUA M25B38/004, B38592
import pandas as pd
from pandas import Series, DataFrame

In [88]:
##1.Series are a one dimensionsal array while a dataFrame is a two dimensional labeled table. 
## A serie is a simple column while a dataFrame is two or more columns combined for example:
pets =Series([ "Cat", "Dog", "Fish", "Turtle"],index =["a", "b", "c", "d"])
print(pets)
df1= DataFrame(pets)
print(df1)

a       Cat
b       Dog
c      Fish
d    Turtle
dtype: object
        0
a     Cat
b     Dog
c    Fish
d  Turtle


In [89]:
##2. .loc[] and .iloc[]: both are used for refernecing but the .loc[] function uses column names and row names 
##     while the .iloc[] function uses row and columns numbers for example;
data = { "Name": ["Hailey", "Billie", "Ashely"], "Age": [21, 23, 19]}
df = pd. DataFrame(data, index = ["x", "y", "z"])
print(df)
print(df.loc["x", "Age"])
print(df.iloc[0,0])

     Name  Age
x  Hailey   21
y  Billie   23
z  Ashely   19
21
Hailey


In [90]:
## 3. The NumPy array is faster because it has optimized C backend than the the python list and the pyhton list has a higher storage usage because it stores references
## while the NumPy array uses lower storage usage becasue it is more compact

In [140]:
##4. the isnull() function is used to checke for missing values in a dataset and returns a boolean function; true for when a value is missing and false when no value is missing.
## notnull() checks for non-missing values and also returns a boolean value: true when no value is missing and false when a value is missing.
## fillna()this is used to fill in the missing values with a value that has been specified by entering it into the parentheses.
##EXAMPLE
import numpy as np
df = pd.DataFrame({ "Cars" : ["Benz", "Toyota", "Prius"], "Year":[ 2003, None, 1998]})
print(df.isnull())
print(df.notnull())
print(df.fillna(2003).round(0))

    Cars   Year
0  False  False
1  False   True
2  False  False
   Cars   Year
0  True   True
1  True  False
2  True   True
     Cars    Year
0    Benz  2003.0
1  Toyota  2003.0
2   Prius  1998.0


In [92]:
##SECTION B

In [147]:
##number 1

list1 =[1,3,4,5,7,33,2,80,45,24]
custom_index =["A", "b", "c", "d", "e", "f", "g", "h", "i", "j"]
list = Series(list1, index=custom_index)
max = list.max()
low = list.min()
print(low)
def square(x):
    return x **2
squared = list.apply(square)
print(squared)
print(max)
print(list[-3:])
print(list[list>50])
list2 = list.rename("Scores")

1
A       1
b       9
c      16
d      25
e      49
f    1089
g       4
h    6400
i    2025
j     576
dtype: int64
80
h    80
i    45
j    24
dtype: int64
h    80
dtype: int64


In [133]:
##number 2
data = {
  "Name": ["Anna", "Ben", "Cathy", "Derek", "Eva"],
 "Age": [22, 25, 23, 24, 21],
 "Gender": ["F", "M", "F", "M", "F"],
 "Score": [89, 94, 75, None, 83]}
df2= pd.DataFrame(data, index = ["Anna", "Ben", "Cathy", "Derek", "Eva"])
print(df2)
print(df2[df2["Score"]>80])
G = df2.drop("Gender", axis = 1)
print(G)
print(df2.describe().round(2))
print(df2["Score"].fillna(df2["Score"].mean()))

        Name  Age Gender  Score
Anna    Anna   22      F   89.0
Ben      Ben   25      M   94.0
Cathy  Cathy   23      F   75.0
Derek  Derek   24      M    NaN
Eva      Eva   21      F   83.0
      Name  Age Gender  Score
Anna  Anna   22      F   89.0
Ben    Ben   25      M   94.0
Eva    Eva   21      F   83.0
        Name  Age  Score
Anna    Anna   22   89.0
Ben      Ben   25   94.0
Cathy  Cathy   23   75.0
Derek  Derek   24    NaN
Eva      Eva   21   83.0
         Age  Score
count   5.00   4.00
mean   23.00  85.25
std     1.58   8.18
min    21.00  75.00
25%    22.00  81.00
50%    23.00  86.00
75%    24.00  90.25
max    25.00  94.00
Anna     89.00
Ben      94.00
Cathy    75.00
Derek    85.25
Eva      83.00
Name: Score, dtype: float64


In [148]:
##number 3

list2 = ([1,2,3,4], [6,7,10,22], [33,56,32,16])
arr1 = np.array(list2)
list3 = DataFrame(arr1, columns = ["C1","C2","C3","C4"], index =["R1", "R2", "R3"])
Replace = list3[list3>0].fillna(0)
print(Replace)
print(list3)
print(arr1)
from math import sqrt
frame4 = list3.applymap(lambda x: sqrt)
print(frame4)
sorted = list3.sort_values(by="C2", ascending = False)
print(sorted)

    C1  C2  C3  C4
R1   1   2   3   4
R2   6   7  10  22
R3  33  56  32  16
    C1  C2  C3  C4
R1   1   2   3   4
R2   6   7  10  22
R3  33  56  32  16
[[ 1  2  3  4]
 [ 6  7 10 22]
 [33 56 32 16]]
                          C1                        C2  \
R1  <built-in function sqrt>  <built-in function sqrt>   
R2  <built-in function sqrt>  <built-in function sqrt>   
R3  <built-in function sqrt>  <built-in function sqrt>   

                          C3                        C4  
R1  <built-in function sqrt>  <built-in function sqrt>  
R2  <built-in function sqrt>  <built-in function sqrt>  
R3  <built-in function sqrt>  <built-in function sqrt>  
    C1  C2  C3  C4
R3  33  56  32  16
R2   6   7  10  22
R1   1   2   3   4


C:\Users\user\AppData\Local\Temp\ipykernel_15368\144604770.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame4 = list3.applymap(lambda x: sqrt)


In [128]:
##number 4

arr2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(arr2d[:-1])
print(arr2d[1, -2:])
row_labels =["R1", "R2", "R5"]
col_labels =[ "Col1", "Col2", "Col3"]
df4 = pd. DataFrame(arr2d, index =row_labels, columns = col_labels)
print(df4)
print(df4.loc["R5"])
list3 = list3.where(list3<= 30, 100)

[[ 5 10 15]
 [20 25 30]]
[25 30]
    Col1  Col2  Col3
R1     5    10    15
R2    20    25    30
R5    35    40    45
Col1    35
Col2    40
Col3    45
Name: R5, dtype: int32


In [163]:
## Number 6

df = pd.DataFrame({
 'Math': [78, 89, 92], 'Physics': [84, 76, 88],'Chemistry': [90, 85, 91]}, 
index=['Alice', 'Bob', 'Charlie'])
                  ## definig the function
def max_minus_min(row):
    return row.max() - row.min()
## application
df["Range"] = df.apply(max_minus_min, axis = 1)
print(df)
print(df["Range"])

         Math  Physics  Chemistry  Range
Alice      78       84         90     12
Bob        89       76         85     13
Charlie    92       88         91      4
Alice      12
Bob        13
Charlie     4
Name: Range, dtype: int64


In [164]:
##number 6

def square(x):
    return x**2
squared = df.applymap(square)
print(squared)
mean = df.mean(axis = 0).round(2)
print(mean)
print(mean.max())

         Math  Physics  Chemistry  Range
Alice    6084     7056       8100    144
Bob      7921     5776       7225    169
Charlie  8464     7744       8281     16
Math         86.33
Physics      82.67
Chemistry    88.67
Range         9.67
dtype: float64
88.67


C:\Users\user\AppData\Local\Temp\ipykernel_15368\2031663700.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  squared = df.applymap(square)


In [129]:
##Number 5

In [162]:
 df = pd.DataFrame({'A': [1, np.nan, 3, np.nan],
 'B': [np.nan, 2, 3, 4],
 'C': [1, 2, np.nan, 4] })
print(df)
clear = df.dropna(axis = 1, how="all")
print(clear)
print(df.fillna(0))
print(df.fillna(df.mean(numeric_only = True).round(2)))
## We use the .notnull() to find out the values that are not null
no_null = (df.notnull())
print(no_null)

     A    B    C
0  1.0  NaN  1.0
1  NaN  2.0  2.0
2  3.0  3.0  NaN
3  NaN  4.0  4.0
     A    B    C
0  1.0  NaN  1.0
1  NaN  2.0  2.0
2  3.0  3.0  NaN
3  NaN  4.0  4.0
     A    B    C
0  1.0  0.0  1.0
1  0.0  2.0  2.0
2  3.0  3.0  0.0
3  0.0  4.0  4.0
     A    B     C
0  1.0  3.0  1.00
1  2.0  2.0  2.00
2  3.0  3.0  2.33
3  2.0  4.0  4.00
       A      B      C
0   True  False   True
1  False   True   True
2   True   True  False
3  False   True   True


In [ ]:
##KABUNGA AKRAM JOSHUA M25B38/004, B32895